/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TareasRouteImport } from './routes/tareas'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DatosRouteImport } from './routes/datos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesNuevoRouteImport } from './routes/clientes.nuevo'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as ApiPublicLeadFormRouteImport } from './routes/api/public/lead-form'
import { Route as ApiPublicBootstrapRouteImport } from './routes/api/public/bootstrap'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TareasRoute = TareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DatosRoute = DatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesNuevoRoute = ClientesNuevoRouteImport.update({
  id: '/clientes/nuevo',
  path: '/clientes/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadFormRoute = ApiPublicLeadFormRouteImport.update({
  id: '/api/public/lead-form',
  path: '/api/public/lead-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapRoute = ApiPublicBootstrapRouteImport.update({
  id: '/api/public/bootstrap',
  path: '/api/public/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datos': typeof DatosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/pipeline': typeof PipelineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tareas': typeof TareasRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/nuevo': typeof ClientesNuevoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/api/public/lead-form': typeof ApiPublicLeadFormRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datos': typeof DatosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/pipeline': typeof PipelineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tareas': typeof TareasRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/nuevo': typeof ClientesNuevoRoute
  '/clientes': typeof ClientesIndexRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/api/public/lead-form': typeof ApiPublicLeadFormRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datos': typeof DatosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/pipeline': typeof PipelineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tareas': typeof TareasRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/nuevo': typeof ClientesNuevoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/api/public/lead-form': typeof ApiPublicLeadFormRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datos'
    | '/login'
    | '/perfil'
    | '/pipeline'
    | '/reset-password'
    | '/tareas'
    | '/clientes/$id'
    | '/clientes/nuevo'
    | '/clientes/'
    | '/api/public/bootstrap'
    | '/api/public/lead-form'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datos'
    | '/login'
    | '/perfil'
    | '/pipeline'
    | '/reset-password'
    | '/tareas'
    | '/clientes/$id'
    | '/clientes/nuevo'
    | '/clientes'
    | '/api/public/bootstrap'
    | '/api/public/lead-form'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/datos'
    | '/login'
    | '/perfil'
    | '/pipeline'
    | '/reset-password'
    | '/tareas'
    | '/clientes/$id'
    | '/clientes/nuevo'
    | '/clientes/'
    | '/api/public/bootstrap'
    | '/api/public/lead-form'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatosRoute: typeof DatosRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  PipelineRoute: typeof PipelineRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TareasRoute: typeof TareasRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ClientesNuevoRoute: typeof ClientesNuevoRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ApiPublicBootstrapRoute: typeof ApiPublicBootstrapRoute
  ApiPublicLeadFormRoute: typeof ApiPublicLeadFormRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tareas': {
      id: '/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof TareasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datos': {
      id: '/datos'
      path: '/datos'
      fullPath: '/datos'
      preLoaderRoute: typeof DatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/nuevo': {
      id: '/clientes/nuevo'
      path: '/clientes/nuevo'
      fullPath: '/clientes/nuevo'
      preLoaderRoute: typeof ClientesNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-form': {
      id: '/api/public/lead-form'
      path: '/api/public/lead-form'
      fullPath: '/api/public/lead-form'
      preLoaderRoute: typeof ApiPublicLeadFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap': {
      id: '/api/public/bootstrap'
      path: '/api/public/bootstrap'
      fullPath: '/api/public/bootstrap'
      preLoaderRoute: typeof ApiPublicBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatosRoute: DatosRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  PipelineRoute: PipelineRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TareasRoute: TareasRoute,
  ClientesIdRoute: ClientesIdRoute,
  ClientesNuevoRoute: ClientesNuevoRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ApiPublicBootstrapRoute: ApiPublicBootstrapRoute,
  ApiPublicLeadFormRoute: ApiPublicLeadFormRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
