
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS origen TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS red_social TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS fecha_hold DATE,
  ADD COLUMN IF NOT EXISTS valor_producto NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_envio NUMERIC NOT NULL DEFAULT 0;

ALTER TABLE public.tareas
  ADD COLUMN IF NOT EXISTS hora TEXT DEFAULT '';
